interfaces:

 - name: Ethernet0/0
   description: Link to R1 configured by Ansible
   ipv4: 10.10.0.2/29
   mode: "L3"

 - name: Loopback 2
   description: Loopback 2 configured by Ansible
   ipv4: 10.10.2.1/24
   ospf: p2p

 - name: Loopback 3
   description: Loopback 3 configured by Ansible
   ipv4: 10.10.3.1/24
   ospf: p2p

# router ospf 123
#  router-id 1.1.1.2
#  auto-cost reference-bandwidth 1000
#  network 10.10.0.0 0.0.3.255 area 0
#  exit

ospf:
  process_id: 123
  router_id: 1.1.1.2
  default_orignate: "False"
  auto_cost:
    reference_bandwidth: 1000
ospf_networks:
    - address: "10.10.0.0"
      wildcard_bits: "0.0.3.255"
      area: "0"
