interfaces:

 - name: Ethernet0/0
   description: Link to R1 configured by Ansible
   ipv4: 10.10.4.2/30
   mode: "L3"

 - name: Loopback 16
   description: Loopback 16 configured by Ansible
   ipv4: 10.10.16.1/24
   ospf: p2p

 - name: Loopback 17
   description: Loopback 17 configured by Ansible
   ipv4: 10.10.17.1/24
   ospf: p2p
   
 - name: Loopback 18
   description: Loopback 18 configured by Ansible
   ipv4: 10.10.18.1/24
   ospf: p2p
   
 - name: Loopback 19
   description: Loopback 19 configured by Ansible
   ipv4: 10.10.19.1/24
   ospf: p2p
   
 - name: Loopback 20
   description: Loopback 20 configured by Ansible
   ipv4: 10.10.20.1/24
   ospf: p2p
   
 - name: Loopback 21
   description: Loopback 21 configured by Ansible
   ipv4: 10.10.21.1/24
   ospf: p2p
   
 - name: Loopback 22
   description: Loopback 22 configured by Ansible
   ipv4: 10.10.22.1/24
   ospf: p2p
   
 - name: Loopback 23
   description: Loopback 23 configured by Ansible
   ipv4: 10.10.23.1/24
   ospf: p2p
   
ospf:
  process_id: 123
  router_id: 3.3.3.2
  default_orignate: "False"
  auto_cost:
    reference_bandwidth: 1000
ospf_networks:
    - address: "10.10.4.0"
      wildcard_bits: "0.0.0.3"
      area: "0"
    - address: "10.10.16.0"
      wildcard_bits: "0.0.7.255"
      area: "0"

#  network 10.10.4.0 0.0.1.255 area 0
#  network 10.10.16.0 0.0.7.255 area 0
